(function initDfmsData(globalScope) {
  var ENUMS = {
    turbineStatus: ['Active', 'Inactive', 'Fail'],
    droneCertification: ['Remote Pilot Certificate', 'None'],
    priority: ['Low', 'Medium', 'High', 'Critical'],
    weatherClearance: ['Clear', 'Caution', 'Hold'],
    safetyStatus: ['Clear', 'Crew Conflict', 'Weather Hold', 'Certification Missing', 'Battery Low', 'Wildlife Review', 'Route Review', 'Blocked'],
    missionStatus: ['Not Scheduled', 'Ready', 'Scheduled', 'In Flight', 'Completed', 'Blocked', 'Needs Review'],
    damageSeverity: ['None', 'Minor', 'Moderate', 'Severe', 'Unknown'],
    imageryStatus: ['No imagery', 'Capture pending', 'Images received', 'Review complete'],
    wildlifeRisk: ['Low', 'Medium', 'High']
  };

  var SOURCE_SYSTEMS = [
    { id: 'src-tcms', label: 'Turbine CMS', description: 'Turbine status, last inspection timestamp, and condition history feed.' },
    { id: 'src-weather', label: 'Weather Forecasting System', description: 'Wind speed, wind direction, and weather clearance forecast snapshots.' },
    { id: 'src-hris', label: 'HRIS', description: 'Operator roster, certification, and shift availability records.' },
    { id: 'src-drone', label: 'Drone Vendor App', description: 'Drone battery telemetry, payload profile, and readiness state.' },
    { id: 'src-maint', label: 'Maintenance Schedule', description: 'Crew onsite windows, conflict markers, and maintenance planning notes.' },
    { id: 'src-env', label: 'Environmental Layer', description: 'Wildlife sensitivity overlays and route restriction indicators.' },
    { id: 'src-ops', label: 'Manual Ops Note', description: 'Dispatcher-entered verbal coordination and local field clarifications.' }
  ];

  var SITES = [
    { id: 'SITE-CR', name: 'Columbia Ridge', region: 'Inland Northwest', state: 'WA', centerLat: 46.223, centerLon: -119.558, terrainNote: 'Open ridge with seasonal gust corridors.' },
    { id: 'SITE-SF', name: 'Sage Flats', region: 'Basin Corridor', state: 'OR', centerLat: 44.115, centerLon: -120.809, terrainNote: 'Wide flats with crosswind exposure near service roads.' },
    { id: 'SITE-RM', name: 'Red Mesa', region: 'High Plateau', state: 'NM', centerLat: 35.912, centerLon: -107.184, terrainNote: 'Elevated mesa with abrupt thermal shifts.' },
    { id: 'SITE-PH', name: 'Pine Hollow', region: 'Foothill Belt', state: 'ID', centerLat: 43.744, centerLon: -116.231, terrainNote: 'Tree-lined approach lanes and narrow staging pads.' },
    { id: 'SITE-CM', name: 'Cedar Mesa', region: 'Mesa Frontier', state: 'CO', centerLat: 38.905, centerLon: -108.122, terrainNote: 'Dry mesa rim with occasional wildlife migration crossings.' },
    { id: 'SITE-HD', name: 'High Desert Array', region: 'Desert Interior', state: 'NV', centerLat: 39.468, centerLon: -117.016, terrainNote: 'Sparse cover and long transit routes between clusters.' },
    { id: 'SITE-NS', name: 'North Sound Wind', region: 'Coastal Uplands', state: 'WA', centerLat: 48.117, centerLon: -122.643, terrainNote: 'Marine-influenced gusting and moisture variation.' },
    { id: 'SITE-PR', name: 'Palouse Ridge', region: 'Agricultural Hills', state: 'WA', centerLat: 46.731, centerLon: -117.201, terrainNote: 'Rolling hills with variable morning thermals.' }
  ];

  var OPERATORS = [
    { id: 'OP-001', name: 'Maya Chen', certification: 'Remote Pilot Certificate', shift: 'Day', homeSite: 'SITE-CR', status: 'Available' },
    { id: 'OP-002', name: 'Luis Ortega', certification: 'Remote Pilot Certificate', shift: 'Day', homeSite: 'SITE-HD', status: 'Available' },
    { id: 'OP-003', name: 'Priya Shah', certification: 'Remote Pilot Certificate', shift: 'Swing', homeSite: 'SITE-NS', status: 'In Mission' },
    { id: 'OP-004', name: 'Ethan Brooks', certification: 'None', shift: 'Day', homeSite: 'SITE-SF', status: 'Observer Only' },
    { id: 'OP-005', name: 'Jordan Lee', certification: 'Remote Pilot Certificate', shift: 'Swing', homeSite: 'SITE-RM', status: 'Available' },
    { id: 'OP-999', name: 'Unassigned', certification: 'None', shift: 'N/A', homeSite: 'N/A', status: 'Not assigned' }
  ];

  var DRONES = [
    { id: 'DRN-014', label: 'Kestrel 14', modelName: 'AeroSight K4', batteryPercent: 88, signalStrength: 'Strong', status: 'Ready', currentSite: 'SITE-CR', payload: '4K Visual + Thermal', maxSafeWindMph: 33 },
    { id: 'DRN-027', label: 'Kestrel 27', modelName: 'AeroSight K4', batteryPercent: 42, signalStrength: 'Stable', status: 'Ready', currentSite: 'SITE-SF', payload: '4K Visual', maxSafeWindMph: 30 },
    { id: 'DRN-031', label: 'Harrier 31', modelName: 'SkyGrid M2', batteryPercent: 61, signalStrength: 'Strong', status: 'Ready', currentSite: 'SITE-RM', payload: 'Thermal Focus', maxSafeWindMph: 36 },
    { id: 'DRN-044', label: 'Harrier 44', modelName: 'SkyGrid M2', batteryPercent: 27, signalStrength: 'Intermittent', status: 'Charging', currentSite: 'SITE-PH', payload: 'Visual Zoom', maxSafeWindMph: 32 },
    { id: 'DRN-052', label: 'Falcon 52', modelName: 'VectorWind X1', batteryPercent: 73, signalStrength: 'Strong', status: 'Ready', currentSite: 'SITE-CM', payload: '4K Visual + LiDAR', maxSafeWindMph: 35 },
    { id: 'DRN-063', label: 'Falcon 63', modelName: 'VectorWind X1', batteryPercent: 55, signalStrength: 'Stable', status: 'In Flight', currentSite: 'SITE-NS', payload: '4K Visual + Thermal', maxSafeWindMph: 34 },
    { id: 'Unassigned', label: 'Unassigned Drone', modelName: 'N/A', batteryPercent: 0, signalStrength: 'N/A', status: 'Unavailable', currentSite: 'N/A', payload: 'N/A', maxSafeWindMph: 0 }
  ];

  var FIELD_DEFINITIONS = {
    missionId: { label: 'Mission ID', type: 'string', editable: false, source: 'Manual Ops Note', note: 'Unique dispatch mission identifier for grid row tracking.' },
    turbineId: { label: 'Turbine ID', type: 'string', editable: false, source: 'Turbine CMS', note: 'Six-digit turbine asset identifier.' },
    siteId: { label: 'Site ID', type: 'string', editable: false, source: 'Turbine CMS', note: 'Internal site reference key used for joins.' },
    siteName: { label: 'Site Name', type: 'string', editable: false, derivedFrom: ['siteId'], note: 'Human-readable wind farm name.' },
    region: { label: 'Region', type: 'string', editable: false, source: 'Turbine CMS', note: 'Operational planning region for the site.' },
    turbineLocation: { label: 'Turbine Location', type: 'object', editable: false, source: 'Turbine CMS', note: 'Static latitude/longitude point for turbine map placement.' },
    turbineStatus: { label: 'Turbine Status', type: 'enum', editable: false, source: 'Turbine CMS', allowedValues: ENUMS.turbineStatus, note: 'Condition state imported from turbine monitoring systems.' },
    lastInspection: { label: 'Last Inspection', type: 'string', editable: false, source: 'Turbine CMS', note: 'ISO-like timestamp of most recent inspection event.' },
    priority: { label: 'Priority', type: 'enum', editable: true, source: 'Manual Ops Note', allowedValues: ENUMS.priority, note: 'Dispatcher planning urgency level.' },
    damageSeverity: { label: 'Damage Severity', type: 'enum', editable: false, source: 'Turbine CMS', allowedValues: ENUMS.damageSeverity, note: 'Latest observed component damage estimate.' },
    temperatureF: { label: 'Temperature (F)', type: 'number', editable: false, source: 'Weather Forecasting System', note: 'Forecast temperature at planned inspection window.' },
    windSpeedMph: { label: 'Wind Speed (mph)', type: 'number', editable: false, source: 'Weather Forecasting System', note: 'Forecast sustained wind speed for mission window.' },
    windDirection: { label: 'Wind Direction', type: 'string', editable: false, source: 'Weather Forecasting System', note: 'Compass direction for forecast wind.' },
    weatherClearance: { label: 'Weather Clearance', type: 'enum', editable: false, source: 'Weather Forecasting System', allowedValues: ENUMS.weatherClearance, note: 'Safety-oriented weather readiness classification.' },
    assignedDroneId: { label: 'Assigned Drone', type: 'string', editable: true, source: 'Drone Vendor App', note: 'Drone allocation for mission execution.' },
    droneBatteryPercent: { label: 'Drone Battery %', type: 'number', editable: false, source: 'Drone Vendor App', note: 'Latest preflight battery reading for assigned drone.' },
    assignedOperatorId: { label: 'Assigned Operator', type: 'string', editable: true, source: 'HRIS', note: 'Operator planned to pilot or supervise mission.' },
    operatorCertification: { label: 'Operator Certification', type: 'enum', editable: false, source: 'HRIS', allowedValues: ENUMS.droneCertification, note: 'Certification eligibility for dispatch operations.' },
    crewOnsite: { label: 'Crew Onsite', type: 'boolean', editable: false, source: 'Maintenance Schedule', note: 'Whether maintenance personnel are actively onsite.' },
    wildlifeRisk: { label: 'Wildlife Risk', type: 'enum', editable: false, source: 'Environmental Layer', allowedValues: ENUMS.wildlifeRisk, note: 'Environmental sensitivity indicator for mission area.' },
    carbonSavingsKg: { label: 'Carbon Savings (kg)', type: 'number', editable: false, derivedFrom: ['routeDistanceMiles'], note: 'Estimated avoided emissions versus truck-only inspection.' },
    imageryStatus: { label: 'Imagery Status', type: 'enum', editable: true, source: 'Drone Vendor App', allowedValues: ENUMS.imageryStatus, note: 'Inspection imagery ingest and review workflow state.' },
    imageCount: { label: 'Image Count', type: 'number', editable: false, source: 'Drone Vendor App', note: 'Number of captured inspection images attached to mission.' },
    routeDistanceMiles: { label: 'Route Distance (mi)', type: 'number', editable: false, source: 'Drone Vendor App', note: 'Planned one-way route distance for mission flight path.' },
    estimatedInspectionMinutes: { label: 'Estimated Inspection (min)', type: 'number', editable: true, source: 'Manual Ops Note', note: 'Planned total inspection duration estimate.' },
    safetyStatus: { label: 'Safety Status', type: 'enum', editable: false, derivedFrom: ['weatherClearance', 'crewOnsite', 'operatorCertification', 'droneBatteryPercent', 'wildlifeRisk', 'flightPath'], allowedValues: ENUMS.safetyStatus, note: 'Primary blocker/safety summary for dispatch decisioning.' },
    missionStatus: { label: 'Mission Status', type: 'enum', editable: true, source: 'Manual Ops Note', allowedValues: ENUMS.missionStatus, note: 'Overall mission workflow state in dispatch grid.' },
    sourceSystems: { label: 'Source Systems', type: 'array', editable: false, derivedFrom: SOURCE_SYSTEMS.map(function (s) { return s.label; }), note: 'Simulated provenance list for major mission fields.' },
    lastSync: { label: 'Last Sync', type: 'string', editable: false, derivedFrom: ['sourceSystems'], note: 'Most recent data refresh timestamp shown to operator.' },
    opsNote: { label: 'Ops Note', type: 'string', editable: true, source: 'Manual Ops Note', note: 'Dispatcher-entered coordination notes and caveats.' },
    flightPath: { label: 'Flight Path', type: 'object', editable: false, source: 'Drone Vendor App', note: 'Static route metadata for map/detail rendering in future tickets.' }
  };

  var SAMPLE_MISSIONS = [
    { missionId: 'MIS-1001', turbineId: '100211', siteId: 'SITE-CR', siteName: 'Columbia Ridge', region: 'Inland Northwest', turbineLocation: { lat: 46.231, lon: -119.549 }, turbineStatus: 'Active', lastInspection: '2026-05-02T09:40:00Z', priority: 'Medium', damageSeverity: 'Minor', temperatureF: 63, windSpeedMph: 17, windDirection: 'NW', weatherClearance: 'Clear', assignedDroneId: 'DRN-014', assignedDroneLabel: 'Kestrel 14', droneBatteryPercent: 88, assignedOperatorId: 'OP-001', operatorName: 'Maya Chen', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'No maintenance crew in turbine row C2.', wildlifeRisk: 'Low', carbonSavingsKg: 21.4, imageryStatus: 'Capture pending', imageCount: 0, routeDistanceMiles: 2.4, estimatedInspectionMinutes: 34, safetyStatus: 'Clear', missionStatus: 'Ready', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule', 'Environmental Layer'], lastSync: '2026-05-26T06:05:00Z', opsNote: 'Ready for morning dispatch window.', flightPath: { routeName: 'CR-C2-Loop', status: 'Validated', waypoints: 6, restrictedAreaOverlap: false, routePreviewLabel: 'Ridge perimeter sweep' }, inspectionImages: [{ label: 'Planned pass A', status: 'Pending', finding: 'Awaiting capture' }] },
    { missionId: 'MIS-1002', turbineId: '100457', siteId: 'SITE-SF', siteName: 'Sage Flats', region: 'Basin Corridor', turbineLocation: { lat: 44.121, lon: -120.794 }, turbineStatus: 'Active', lastInspection: '2026-04-19T14:12:00Z', priority: 'High', damageSeverity: 'Moderate', temperatureF: 57, windSpeedMph: 38, windDirection: 'W', weatherClearance: 'Hold', assignedDroneId: 'DRN-027', assignedDroneLabel: 'Kestrel 27', droneBatteryPercent: 42, assignedOperatorId: 'OP-002', operatorName: 'Luis Ortega', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Crew staged offsite pending weather.', wildlifeRisk: 'Low', carbonSavingsKg: 18.2, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 1.9, estimatedInspectionMinutes: 29, safetyStatus: 'Weather Hold', missionStatus: 'Blocked', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T06:03:00Z', opsNote: 'Hold until gusts drop below drone envelope.', flightPath: { routeName: 'SF-W1-Arc', status: 'Paused', waypoints: 5, restrictedAreaOverlap: false, routePreviewLabel: 'West arc inspection' }, inspectionImages: [] },
    { missionId: 'MIS-1003', turbineId: '100804', siteId: 'SITE-RM', siteName: 'Red Mesa', region: 'High Plateau', turbineLocation: { lat: 35.918, lon: -107.172 }, turbineStatus: 'Active', lastInspection: '2026-05-09T11:21:00Z', priority: 'High', damageSeverity: 'Unknown', temperatureF: 71, windSpeedMph: 14, windDirection: 'SW', weatherClearance: 'Clear', assignedDroneId: 'DRN-031', assignedDroneLabel: 'Harrier 31', droneBatteryPercent: 61, assignedOperatorId: 'OP-004', operatorName: 'Ethan Brooks', operatorCertification: 'None', crewOnsite: false, crewLocationNote: 'No conflict with current crew calendar.', wildlifeRisk: 'Medium', carbonSavingsKg: 16.7, imageryStatus: 'Capture pending', imageCount: 0, routeDistanceMiles: 2.1, estimatedInspectionMinutes: 33, safetyStatus: 'Certification Missing', missionStatus: 'Blocked', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T05:59:00Z', opsNote: 'Awaiting certified pilot reassignment.', flightPath: { routeName: 'RM-E3-Check', status: 'Validated', waypoints: 7, restrictedAreaOverlap: false, routePreviewLabel: 'East string climb' }, inspectionImages: [{ label: 'Template frame', status: 'Pending', finding: 'No capture yet' }] },
    { missionId: 'MIS-1004', turbineId: '101122', siteId: 'SITE-PH', siteName: 'Pine Hollow', region: 'Foothill Belt', turbineLocation: { lat: 43.751, lon: -116.226 }, turbineStatus: 'Active', lastInspection: '2026-05-18T08:05:00Z', priority: 'Medium', damageSeverity: 'Minor', temperatureF: 60, windSpeedMph: 12, windDirection: 'N', weatherClearance: 'Clear', assignedDroneId: 'DRN-052', assignedDroneLabel: 'Falcon 52', droneBatteryPercent: 73, assignedOperatorId: 'OP-005', operatorName: 'Jordan Lee', operatorCertification: 'Remote Pilot Certificate', crewOnsite: true, crewLocationNote: 'Blade repair crew in adjacent aisle until 10:30 UTC.', wildlifeRisk: 'Low', carbonSavingsKg: 14.9, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 1.6, estimatedInspectionMinutes: 25, safetyStatus: 'Crew Conflict', missionStatus: 'Blocked', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T06:00:00Z', opsNote: 'Reschedule after crew clears tower corridor.', flightPath: { routeName: 'PH-N2-Circle', status: 'Validated', waypoints: 4, restrictedAreaOverlap: false, routePreviewLabel: 'North tower circle' }, inspectionImages: [] },
    { missionId: 'MIS-1005', turbineId: '101307', siteId: 'SITE-CM', siteName: 'Cedar Mesa', region: 'Mesa Frontier', turbineLocation: { lat: 38.913, lon: -108.135 }, turbineStatus: 'Active', lastInspection: '2026-05-04T13:37:00Z', priority: 'High', damageSeverity: 'Moderate', temperatureF: 69, windSpeedMph: 16, windDirection: 'SE', weatherClearance: 'Caution', assignedDroneId: 'DRN-052', assignedDroneLabel: 'Falcon 52', droneBatteryPercent: 73, assignedOperatorId: 'OP-002', operatorName: 'Luis Ortega', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'No maintenance overlap; environmental observer requested.', wildlifeRisk: 'High', carbonSavingsKg: 20.1, imageryStatus: 'Images received', imageCount: 9, routeDistanceMiles: 2.7, estimatedInspectionMinutes: 36, safetyStatus: 'Wildlife Review', missionStatus: 'Needs Review', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Environmental Layer', 'Maintenance Schedule'], lastSync: '2026-05-26T06:07:00Z', opsNote: 'Falcon nesting alert in sector south ridge.', flightPath: { routeName: 'CM-SR-Transit', status: 'Review Required', waypoints: 8, restrictedAreaOverlap: true, routePreviewLabel: 'South ridge traverse' }, inspectionImages: [{ label: 'CM frame 01', status: 'Received', finding: 'Leading edge wear' }, { label: 'CM frame 02', status: 'Received', finding: 'No major crack visible' }] },
    { missionId: 'MIS-1006', turbineId: '101410', siteId: 'SITE-HD', siteName: 'High Desert Array', region: 'Desert Interior', turbineLocation: { lat: 39.473, lon: -117.025 }, turbineStatus: 'Active', lastInspection: '2026-05-01T10:48:00Z', priority: 'Medium', damageSeverity: 'Unknown', temperatureF: 74, windSpeedMph: 13, windDirection: 'E', weatherClearance: 'Clear', assignedDroneId: 'DRN-044', assignedDroneLabel: 'Harrier 44', droneBatteryPercent: 27, assignedOperatorId: 'OP-002', operatorName: 'Luis Ortega', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Crew not onsite; battery swap needed before launch.', wildlifeRisk: 'Low', carbonSavingsKg: 17.8, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 2.0, estimatedInspectionMinutes: 30, safetyStatus: 'Battery Low', missionStatus: 'Blocked', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App'], lastSync: '2026-05-26T06:02:00Z', opsNote: 'Queue battery replacement then re-evaluate launch.', flightPath: { routeName: 'HD-E1-Direct', status: 'Validated', waypoints: 5, restrictedAreaOverlap: false, routePreviewLabel: 'East line direct route' }, inspectionImages: [] },
    { missionId: 'MIS-1007', turbineId: '101512', siteId: 'SITE-NS', siteName: 'North Sound Wind', region: 'Coastal Uplands', turbineLocation: { lat: 48.109, lon: -122.635 }, turbineStatus: 'Fail', lastInspection: '2026-05-21T16:22:00Z', priority: 'Critical', damageSeverity: 'Severe', temperatureF: 55, windSpeedMph: 20, windDirection: 'NW', weatherClearance: 'Caution', assignedDroneId: 'DRN-063', assignedDroneLabel: 'Falcon 63', droneBatteryPercent: 55, assignedOperatorId: 'OP-003', operatorName: 'Priya Shah', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Emergency maintenance team on standby at base camp.', wildlifeRisk: 'Medium', carbonSavingsKg: 24.3, imageryStatus: 'Images received', imageCount: 14, routeDistanceMiles: 3.4, estimatedInspectionMinutes: 42, safetyStatus: 'Clear', missionStatus: 'Scheduled', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T06:08:00Z', opsNote: 'Critical failure escalation acknowledged by operations lead.', flightPath: { routeName: 'NS-Failover-1', status: 'Validated', waypoints: 9, restrictedAreaOverlap: false, routePreviewLabel: 'Coastal urgent corridor' }, inspectionImages: [{ label: 'NS crack panel', status: 'Received', finding: 'Severe trailing-edge split' }] },
    { missionId: 'MIS-1008', turbineId: '101688', siteId: 'SITE-PR', siteName: 'Palouse Ridge', region: 'Agricultural Hills', turbineLocation: { lat: 46.724, lon: -117.214 }, turbineStatus: 'Active', lastInspection: '2025-11-11T12:00:00Z', priority: 'High', damageSeverity: 'Minor', temperatureF: 64, windSpeedMph: 18, windDirection: 'W', weatherClearance: 'Caution', assignedDroneId: 'DRN-014', assignedDroneLabel: 'Kestrel 14', droneBatteryPercent: 88, assignedOperatorId: 'OP-001', operatorName: 'Maya Chen', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'No crew overlap; overdue inspection flagged in queue.', wildlifeRisk: 'Low', carbonSavingsKg: 19.2, imageryStatus: 'Capture pending', imageCount: 0, routeDistanceMiles: 2.9, estimatedInspectionMinutes: 38, safetyStatus: 'Clear', missionStatus: 'Ready', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T06:06:00Z', opsNote: 'Overdue by maintenance SLA; prioritize this cycle.', flightPath: { routeName: 'PR-Overdue-2', status: 'Validated', waypoints: 7, restrictedAreaOverlap: false, routePreviewLabel: 'Hillline overdue sweep' }, inspectionImages: [{ label: 'Preflight card', status: 'Pending', finding: 'Awaiting capture' }] },
    { missionId: 'MIS-1009', turbineId: '101799', siteId: 'SITE-SF', siteName: 'Sage Flats', region: 'Basin Corridor', turbineLocation: { lat: 44.108, lon: -120.817 }, turbineStatus: 'Inactive', lastInspection: '2026-05-16T15:41:00Z', priority: 'Low', damageSeverity: 'None', temperatureF: 61, windSpeedMph: 11, windDirection: 'NE', weatherClearance: 'Clear', assignedDroneId: 'DRN-027', assignedDroneLabel: 'Kestrel 27', droneBatteryPercent: 42, assignedOperatorId: 'OP-005', operatorName: 'Jordan Lee', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Inspection aligned with planned recommissioning next week.', wildlifeRisk: 'Low', carbonSavingsKg: 12.6, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 1.4, estimatedInspectionMinutes: 24, safetyStatus: 'Clear', missionStatus: 'Scheduled', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T05:57:00Z', opsNote: 'Scheduled for later inspection before restart.', flightPath: { routeName: 'SF-Restore-Lite', status: 'Validated', waypoints: 4, restrictedAreaOverlap: false, routePreviewLabel: 'Recommission quick loop' }, inspectionImages: [] },
    { missionId: 'MIS-1010', turbineId: '101845', siteId: 'SITE-NS', siteName: 'North Sound Wind', region: 'Coastal Uplands', turbineLocation: { lat: 48.123, lon: -122.651 }, turbineStatus: 'Active', lastInspection: '2026-05-20T09:14:00Z', priority: 'Medium', damageSeverity: 'Minor', temperatureF: 54, windSpeedMph: 15, windDirection: 'NW', weatherClearance: 'Clear', assignedDroneId: 'DRN-063', assignedDroneLabel: 'Falcon 63', droneBatteryPercent: 55, assignedOperatorId: 'OP-003', operatorName: 'Priya Shah', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Live mission corridor clear.', wildlifeRisk: 'Low', carbonSavingsKg: 15.8, imageryStatus: 'Images received', imageCount: 6, routeDistanceMiles: 2.2, estimatedInspectionMinutes: 31, safetyStatus: 'Clear', missionStatus: 'In Flight', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App'], lastSync: '2026-05-26T06:09:00Z', opsNote: 'Telemetry nominal; mission active.', flightPath: { routeName: 'NS-Live-Run-4', status: 'Active', waypoints: 6, restrictedAreaOverlap: false, routePreviewLabel: 'Live coastal lane' }, inspectionImages: [{ label: 'Frame live-01', status: 'Received', finding: 'Surface wear minor' }] },
    { missionId: 'MIS-1011', turbineId: '101932', siteId: 'SITE-CM', siteName: 'Cedar Mesa', region: 'Mesa Frontier', turbineLocation: { lat: 38.899, lon: -108.118 }, turbineStatus: 'Active', lastInspection: '2026-05-23T18:26:00Z', priority: 'Medium', damageSeverity: 'Minor', temperatureF: 68, windSpeedMph: 12, windDirection: 'S', weatherClearance: 'Clear', assignedDroneId: 'DRN-031', assignedDroneLabel: 'Harrier 31', droneBatteryPercent: 61, assignedOperatorId: 'OP-005', operatorName: 'Jordan Lee', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'No onsite conflicts recorded.', wildlifeRisk: 'Low', carbonSavingsKg: 13.5, imageryStatus: 'Review complete', imageCount: 11, routeDistanceMiles: 1.8, estimatedInspectionMinutes: 27, safetyStatus: 'Clear', missionStatus: 'Completed', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule'], lastSync: '2026-05-26T05:56:00Z', opsNote: 'Imagery review closed with minor follow-up only.', flightPath: { routeName: 'CM-Complete-7', status: 'Completed', waypoints: 5, restrictedAreaOverlap: false, routePreviewLabel: 'Completed mesa circuit' }, inspectionImages: [{ label: 'CM post-01', status: 'Reviewed', finding: 'Minor erosion near tip' }, { label: 'CM post-02', status: 'Reviewed', finding: 'No structural crack' }] },
    { missionId: 'MIS-1012', turbineId: '102004', siteId: 'SITE-HD', siteName: 'High Desert Array', region: 'Desert Interior', turbineLocation: { lat: 39.462, lon: -117.003 }, turbineStatus: 'Active', lastInspection: '2026-05-13T07:55:00Z', priority: 'High', damageSeverity: 'Moderate', temperatureF: 76, windSpeedMph: 19, windDirection: 'SE', weatherClearance: 'Caution', assignedDroneId: 'DRN-052', assignedDroneLabel: 'Falcon 52', droneBatteryPercent: 73, assignedOperatorId: 'OP-002', operatorName: 'Luis Ortega', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'Crew clear; caution winds monitored.', wildlifeRisk: 'Low', carbonSavingsKg: 22.8, imageryStatus: 'Capture pending', imageCount: 0, routeDistanceMiles: 3.1, estimatedInspectionMinutes: 40, safetyStatus: 'Clear', missionStatus: 'Ready', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Environmental Layer'], lastSync: '2026-05-26T06:04:00Z', opsNote: 'Proceed with caution weather briefing; no hard blockers.', flightPath: { routeName: 'HD-Caution-9', status: 'Validated', waypoints: 8, restrictedAreaOverlap: false, routePreviewLabel: 'Desert caution route' }, inspectionImages: [{ label: 'Planning overlay', status: 'Pending', finding: 'Capture not started' }] },
    { missionId: 'MIS-1013', turbineId: '102117', siteId: 'SITE-RM', siteName: 'Red Mesa', region: 'High Plateau', turbineLocation: { lat: 35.903, lon: -107.188 }, turbineStatus: 'Active', lastInspection: '2026-05-07T17:11:00Z', priority: 'Medium', damageSeverity: 'Unknown', temperatureF: 70, windSpeedMph: 18, windDirection: 'SW', weatherClearance: 'Clear', assignedDroneId: 'DRN-031', assignedDroneLabel: 'Harrier 31', droneBatteryPercent: 61, assignedOperatorId: 'OP-001', operatorName: 'Maya Chen', operatorCertification: 'Remote Pilot Certificate', crewOnsite: false, crewLocationNote: 'No crew conflict; path intersects temporary survey zone.', wildlifeRisk: 'Medium', carbonSavingsKg: 17.1, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 2.5, estimatedInspectionMinutes: 35, safetyStatus: 'Route Review', missionStatus: 'Needs Review', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Environmental Layer', 'Manual Ops Note'], lastSync: '2026-05-26T06:01:00Z', opsNote: 'Verbal coordination with survey team at 05:50 UTC; await route adjustment confirmation.', flightPath: { routeName: 'RM-Survey-Cross', status: 'Review Required', waypoints: 7, restrictedAreaOverlap: true, routePreviewLabel: 'Survey overlap review lane' }, inspectionImages: [{ label: 'Route placeholder', status: 'Pending', finding: 'Awaiting revised corridor' }] },
    { missionId: 'MIS-1014', turbineId: '102265', siteId: 'SITE-CR', siteName: 'Columbia Ridge', region: 'Inland Northwest', turbineLocation: { lat: 46.216, lon: -119.571 }, turbineStatus: 'Fail', lastInspection: '2026-05-24T06:43:00Z', priority: 'Critical', damageSeverity: 'Severe', temperatureF: 62, windSpeedMph: 26, windDirection: 'W', weatherClearance: 'Hold', assignedDroneId: 'Unassigned', assignedDroneLabel: 'Unassigned Drone', droneBatteryPercent: 0, assignedOperatorId: 'OP-999', operatorName: 'Unassigned', operatorCertification: 'None', crewOnsite: true, crewLocationNote: 'Emergency repair crew and no certified pilot currently assigned.', wildlifeRisk: 'High', carbonSavingsKg: 0, imageryStatus: 'No imagery', imageCount: 0, routeDistanceMiles: 0.1, estimatedInspectionMinutes: 45, safetyStatus: 'Blocked', missionStatus: 'Blocked', sourceSystems: ['Turbine CMS', 'Weather Forecasting System', 'HRIS', 'Drone Vendor App', 'Maintenance Schedule', 'Environmental Layer', 'Manual Ops Note'], lastSync: '2026-05-26T06:10:00Z', opsNote: 'Multiple blockers active; dispatch lead requires escalation meeting.', flightPath: { routeName: 'CR-Escalation-Hold', status: 'Unavailable', waypoints: 0, restrictedAreaOverlap: true, routePreviewLabel: 'No route available until blockers resolved' }, inspectionImages: [] }
  ];

  globalScope.DFMS_DATA = { ENUMS: ENUMS, SOURCE_SYSTEMS: SOURCE_SYSTEMS, DRONES: DRONES, OPERATORS: OPERATORS, SITES: SITES, SAMPLE_MISSIONS: SAMPLE_MISSIONS, FIELD_DEFINITIONS: FIELD_DEFINITIONS };
  globalScope.DFMS_SAMPLE_MISSIONS = SAMPLE_MISSIONS;
})(typeof globalThis !== 'undefined' ? globalThis : window);
